export const PAKISTANI_CITIES = [
  'Islamabad',
  'Rawalpindi',
  'Lahore',
  'Karachi',
  'Faisalabad',
  'Peshawar',
  'Quetta',
  'Multan',
  'Hyderabad',
  'Sialkot',
  'Gujranwala',
  'Abbottabad',
  'Mardan',
  'Sukkur',
  'Bahawalpur',
] as const;
